# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#   
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Major.create(:name => 'Daley', :city => cities.first)

# Abusive Roots
AbusiveRoot.create(:word => 'anus')
AbusiveRoot.create(:word => 'arse')
AbusiveRoot.create(:word => 'ass')
AbusiveRoot.create(:word => 'axwound')
AbusiveRoot.create(:word => 'bampot')
AbusiveRoot.create(:word => 'beaner')
AbusiveRoot.create(:word => 'bitch')
AbusiveRoot.create(:word => 'blow')
AbusiveRoot.create(:word => 'bollocks')
AbusiveRoot.create(:word => 'bollox')
AbusiveRoot.create(:word => 'boner')
AbusiveRoot.create(:word => 'butt')
AbusiveRoot.create(:word => 'camel toe')
AbusiveRoot.create(:word => 'carpetmuncher')
AbusiveRoot.create(:word => 'chesticle')
AbusiveRoot.create(:word => 'chinc')
AbusiveRoot.create(:word => 'chink')
AbusiveRoot.create(:word => 'clit')
AbusiveRoot.create(:word => 'cock')
AbusiveRoot.create(:word => 'coochie')
AbusiveRoot.create(:word => 'coochy')
AbusiveRoot.create(:word => 'coon')
AbusiveRoot.create(:word => 'cooter')
AbusiveRoot.create(:word => 'cracker')
AbusiveRoot.create(:word => 'cum')
AbusiveRoot.create(:word => 'cunnie')
AbusiveRoot.create(:word => 'cunnilingus')
AbusiveRoot.create(:word => 'cunt')
AbusiveRoot.create(:word => 'dago')
AbusiveRoot.create(:word => 'damn')
AbusiveRoot.create(:word => 'deggo')
AbusiveRoot.create(:word => 'dick')
AbusiveRoot.create(:word => 'dike')
AbusiveRoot.create(:word => 'dildo')
AbusiveRoot.create(:word => 'doochbag')
AbusiveRoot.create(:word => 'dookie')
AbusiveRoot.create(:word => 'douche')
AbusiveRoot.create(:word => 'dyke')
AbusiveRoot.create(:word => 'fag')
AbusiveRoot.create(:word => 'fellatio')
AbusiveRoot.create(:word => 'feltch')
AbusiveRoot.create(:word => 'flamer')
AbusiveRoot.create(:word => 'fuck')
AbusiveRoot.create(:word => 'fudgepacker')
AbusiveRoot.create(:word => 'gay')
AbusiveRoot.create(:word => 'gooch')
AbusiveRoot.create(:word => 'gook')
AbusiveRoot.create(:word => 'gringo')
AbusiveRoot.create(:word => 'guido')
AbusiveRoot.create(:word => 'handjob')
AbusiveRoot.create(:word => 'hard on')
AbusiveRoot.create(:word => 'heeb')
AbusiveRoot.create(:word => 'hell')
AbusiveRoot.create(:word => 'humping')
AbusiveRoot.create(:word => 'jagoff')
AbusiveRoot.create(:word => 'jap')
AbusiveRoot.create(:word => 'jerk off')
AbusiveRoot.create(:word => 'jigaboo')
AbusiveRoot.create(:word => 'jizz')
AbusiveRoot.create(:word => 'jungle')
AbusiveRoot.create(:word => 'kike')
AbusiveRoot.create(:word => 'kooch')
AbusiveRoot.create(:word => 'kootch')
AbusiveRoot.create(:word => 'kraut')
AbusiveRoot.create(:word => 'kunt')
AbusiveRoot.create(:word => 'kyke')
AbusiveRoot.create(:word => 'lesbian')
AbusiveRoot.create(:word => 'lesbo')
AbusiveRoot.create(:word => 'lezzie')
AbusiveRoot.create(:word => 'mick')
AbusiveRoot.create(:word => 'minge')
AbusiveRoot.create(:word => 'monkey')
AbusiveRoot.create(:word => 'muff')
AbusiveRoot.create(:word => 'munging')
AbusiveRoot.create(:word => 'negro')
AbusiveRoot.create(:word => 'niga')
AbusiveRoot.create(:word => 'nigaboo')
AbusiveRoot.create(:word => 'nigga')
AbusiveRoot.create(:word => 'niger')
AbusiveRoot.create(:word => 'nigger')
AbusiveRoot.create(:word => 'niglet')
AbusiveRoot.create(:word => 'nut sack')
AbusiveRoot.create(:word => 'nutsack')
AbusiveRoot.create(:word => 'paki')
AbusiveRoot.create(:word => 'panooch')
AbusiveRoot.create(:word => 'pecker')
AbusiveRoot.create(:word => 'penis')
AbusiveRoot.create(:word => 'piss')
AbusiveRoot.create(:word => 'pole')
AbusiveRoot.create(:word => 'pollock')
AbusiveRoot.create(:word => 'poon')
AbusiveRoot.create(:word => 'prick')
AbusiveRoot.create(:word => 'punanny')
AbusiveRoot.create(:word => 'punta')
AbusiveRoot.create(:word => 'pussies')
AbusiveRoot.create(:word => 'pussy')
AbusiveRoot.create(:word => 'puto')
AbusiveRoot.create(:word => 'queef')
AbusiveRoot.create(:word => 'queer')
AbusiveRoot.create(:word => 'renob')
AbusiveRoot.create(:word => 'rimjob')
AbusiveRoot.create(:word => 'ruski')
AbusiveRoot.create(:word => 'schlong')
AbusiveRoot.create(:word => 'scrote')
AbusiveRoot.create(:word => 'shit')
AbusiveRoot.create(:word => 'shiz')
AbusiveRoot.create(:word => 'skank')
AbusiveRoot.create(:word => 'skeet')
AbusiveRoot.create(:word => 'slut')
AbusiveRoot.create(:word => 'smeg')
AbusiveRoot.create(:word => 'snatch')
AbusiveRoot.create(:word => 'spic')
AbusiveRoot.create(:word => 'splooge')
AbusiveRoot.create(:word => 'spook')
AbusiveRoot.create(:word => 'tard')
AbusiveRoot.create(:word => 'testicle')
AbusiveRoot.create(:word => 'tit')
AbusiveRoot.create(:word => 'twat')
AbusiveRoot.create(:word => 'vag')
AbusiveRoot.create(:word => 'vaj')
AbusiveRoot.create(:word => 'wank')
AbusiveRoot.create(:word => 'wetback')
AbusiveRoot.create(:word => 'wop')

# Abusive Tags
Tag.create(:tag => 'anus', :abusive => true)
Tag.create(:tag => 'arse', :abusive => true)
Tag.create(:tag => 'arsehole', :abusive => true)
Tag.create(:tag => 'ass', :abusive => true)
Tag.create(:tag => 'ass-hat', :abusive => true)
Tag.create(:tag => 'ass-jabber', :abusive => true)
Tag.create(:tag => 'ass-pirate', :abusive => true)
Tag.create(:tag => 'assbag', :abusive => true)
Tag.create(:tag => 'assbandit', :abusive => true)
Tag.create(:tag => 'assbanger', :abusive => true)
Tag.create(:tag => 'assbite', :abusive => true)
Tag.create(:tag => 'assclown', :abusive => true)
Tag.create(:tag => 'asscock', :abusive => true)
Tag.create(:tag => 'asscracker', :abusive => true)
Tag.create(:tag => 'asses', :abusive => true)
Tag.create(:tag => 'assface', :abusive => true)
Tag.create(:tag => 'assfuck', :abusive => true)
Tag.create(:tag => 'assfucker', :abusive => true)
Tag.create(:tag => 'assgoblin', :abusive => true)
Tag.create(:tag => 'asshat', :abusive => true)
Tag.create(:tag => 'asshead', :abusive => true)
Tag.create(:tag => 'asshole', :abusive => true)
Tag.create(:tag => 'asshopper', :abusive => true)
Tag.create(:tag => 'assjacker', :abusive => true)
Tag.create(:tag => 'asslick', :abusive => true)
Tag.create(:tag => 'asslicker', :abusive => true)
Tag.create(:tag => 'assmonkey', :abusive => true)
Tag.create(:tag => 'assmunch', :abusive => true)
Tag.create(:tag => 'assmuncher', :abusive => true)
Tag.create(:tag => 'assnigger', :abusive => true)
Tag.create(:tag => 'asspirate', :abusive => true)
Tag.create(:tag => 'assshit', :abusive => true)
Tag.create(:tag => 'assshole', :abusive => true)
Tag.create(:tag => 'asssucker', :abusive => true)
Tag.create(:tag => 'asswad', :abusive => true)
Tag.create(:tag => 'asswipe', :abusive => true)
Tag.create(:tag => 'axwound', :abusive => true)
Tag.create(:tag => 'bampot', :abusive => true)
Tag.create(:tag => 'bastard', :abusive => true)
Tag.create(:tag => 'beaner', :abusive => true)
Tag.create(:tag => 'bitch', :abusive => true)
Tag.create(:tag => 'bitchass', :abusive => true)
Tag.create(:tag => 'bitches', :abusive => true)
Tag.create(:tag => 'bitchtits', :abusive => true)
Tag.create(:tag => 'bitchy', :abusive => true)
Tag.create(:tag => 'blow job', :abusive => true)
Tag.create(:tag => 'blowjob', :abusive => true)
Tag.create(:tag => 'bollocks', :abusive => true)
Tag.create(:tag => 'bollox', :abusive => true)
Tag.create(:tag => 'boner', :abusive => true)
Tag.create(:tag => 'brotherfucker', :abusive => true)
Tag.create(:tag => 'bullshit', :abusive => true)
Tag.create(:tag => 'bumblefuck', :abusive => true)
Tag.create(:tag => 'butt plug', :abusive => true)
Tag.create(:tag => 'butt-pirate', :abusive => true)
Tag.create(:tag => 'buttfucka', :abusive => true)
Tag.create(:tag => 'buttfucker', :abusive => true)
Tag.create(:tag => 'camel toe', :abusive => true)
Tag.create(:tag => 'carpetmuncher', :abusive => true)
Tag.create(:tag => 'chesticle', :abusive => true)
Tag.create(:tag => 'chinc', :abusive => true)
Tag.create(:tag => 'chink', :abusive => true)
Tag.create(:tag => 'choad', :abusive => true)
Tag.create(:tag => 'chode', :abusive => true)
Tag.create(:tag => 'clit', :abusive => true)
Tag.create(:tag => 'clitface', :abusive => true)
Tag.create(:tag => 'clitfuck', :abusive => true)
Tag.create(:tag => 'clusterfuck', :abusive => true)
Tag.create(:tag => 'cock', :abusive => true)
Tag.create(:tag => 'cockass', :abusive => true)
Tag.create(:tag => 'cockbite', :abusive => true)
Tag.create(:tag => 'cockburger', :abusive => true)
Tag.create(:tag => 'cockface', :abusive => true)
Tag.create(:tag => 'cockfucker', :abusive => true)
Tag.create(:tag => 'cockhead', :abusive => true)
Tag.create(:tag => 'cockjockey', :abusive => true)
Tag.create(:tag => 'cockknoker', :abusive => true)
Tag.create(:tag => 'cockmaster', :abusive => true)
Tag.create(:tag => 'cockmongler', :abusive => true)
Tag.create(:tag => 'cockmongruel', :abusive => true)
Tag.create(:tag => 'cockmonkey', :abusive => true)
Tag.create(:tag => 'cockmuncher', :abusive => true)
Tag.create(:tag => 'cocknose', :abusive => true)
Tag.create(:tag => 'cocknugget', :abusive => true)
Tag.create(:tag => 'cockshit', :abusive => true)
Tag.create(:tag => 'cocksmith', :abusive => true)
Tag.create(:tag => 'cocksmoke', :abusive => true)
Tag.create(:tag => 'cocksmoker', :abusive => true)
Tag.create(:tag => 'cocksniffer', :abusive => true)
Tag.create(:tag => 'cocksucker', :abusive => true)
Tag.create(:tag => 'cockwaffle', :abusive => true)
Tag.create(:tag => 'coochie', :abusive => true)
Tag.create(:tag => 'coochy', :abusive => true)
Tag.create(:tag => 'coon', :abusive => true)
Tag.create(:tag => 'cooter', :abusive => true)
Tag.create(:tag => 'cracker', :abusive => true)
Tag.create(:tag => 'cum', :abusive => true)
Tag.create(:tag => 'cumbubble', :abusive => true)
Tag.create(:tag => 'cumdumpster', :abusive => true)
Tag.create(:tag => 'cumguzzler', :abusive => true)
Tag.create(:tag => 'cumjockey', :abusive => true)
Tag.create(:tag => 'cumslut', :abusive => true)
Tag.create(:tag => 'cumtart', :abusive => true)
Tag.create(:tag => 'cunnie', :abusive => true)
Tag.create(:tag => 'cunnilingus', :abusive => true)
Tag.create(:tag => 'cunt', :abusive => true)
Tag.create(:tag => 'cuntass', :abusive => true)
Tag.create(:tag => 'cuntface', :abusive => true)
Tag.create(:tag => 'cunthole', :abusive => true)
Tag.create(:tag => 'cuntlicker', :abusive => true)
Tag.create(:tag => 'cuntrag', :abusive => true)
Tag.create(:tag => 'cuntslut', :abusive => true)
Tag.create(:tag => 'dago', :abusive => true)
Tag.create(:tag => 'damn', :abusive => true)
Tag.create(:tag => 'deggo', :abusive => true)
Tag.create(:tag => 'dick', :abusive => true)
Tag.create(:tag => 'dick-sneeze', :abusive => true)
Tag.create(:tag => 'dickbag', :abusive => true)
Tag.create(:tag => 'dickbeaters', :abusive => true)
Tag.create(:tag => 'dickface', :abusive => true)
Tag.create(:tag => 'dickfuck', :abusive => true)
Tag.create(:tag => 'dickfucker', :abusive => true)
Tag.create(:tag => 'dickhead', :abusive => true)
Tag.create(:tag => 'dickhole', :abusive => true)
Tag.create(:tag => 'dickjuice', :abusive => true)
Tag.create(:tag => 'dickmilk', :abusive => true)
Tag.create(:tag => 'dickmonger', :abusive => true)
Tag.create(:tag => 'dicks', :abusive => true)
Tag.create(:tag => 'dickslap', :abusive => true)
Tag.create(:tag => 'dicksucker', :abusive => true)
Tag.create(:tag => 'dicksucking', :abusive => true)
Tag.create(:tag => 'dicktickler', :abusive => true)
Tag.create(:tag => 'dickwad', :abusive => true)
Tag.create(:tag => 'dickweasel', :abusive => true)
Tag.create(:tag => 'dickweed', :abusive => true)
Tag.create(:tag => 'dickwod', :abusive => true)
Tag.create(:tag => 'dike', :abusive => true)
Tag.create(:tag => 'dildo', :abusive => true)
Tag.create(:tag => 'dipshit', :abusive => true)
Tag.create(:tag => 'doochbag', :abusive => true)
Tag.create(:tag => 'dookie', :abusive => true)
Tag.create(:tag => 'douche', :abusive => true)
Tag.create(:tag => 'douche-fag', :abusive => true)
Tag.create(:tag => 'douchebag', :abusive => true)
Tag.create(:tag => 'douchewaffle', :abusive => true)
Tag.create(:tag => 'dumass', :abusive => true)
Tag.create(:tag => 'dumb ass', :abusive => true)
Tag.create(:tag => 'dumbass', :abusive => true)
Tag.create(:tag => 'dumbfuck', :abusive => true)
Tag.create(:tag => 'dumbshit', :abusive => true)
Tag.create(:tag => 'dumshit', :abusive => true)
Tag.create(:tag => 'dyke', :abusive => true)
Tag.create(:tag => 'fag', :abusive => true)
Tag.create(:tag => 'fagbag', :abusive => true)
Tag.create(:tag => 'fagfucker', :abusive => true)
Tag.create(:tag => 'faggit', :abusive => true)
Tag.create(:tag => 'faggot', :abusive => true)
Tag.create(:tag => 'faggotcock', :abusive => true)
Tag.create(:tag => 'fagtard', :abusive => true)
Tag.create(:tag => 'fatass', :abusive => true)
Tag.create(:tag => 'fellatio', :abusive => true)
Tag.create(:tag => 'feltch', :abusive => true)
Tag.create(:tag => 'flamer', :abusive => true)
Tag.create(:tag => 'fuck', :abusive => true)
Tag.create(:tag => 'fuckass', :abusive => true)
Tag.create(:tag => 'fuckbag', :abusive => true)
Tag.create(:tag => 'fuckboy', :abusive => true)
Tag.create(:tag => 'fuckbrain', :abusive => true)
Tag.create(:tag => 'fuckbutt', :abusive => true)
Tag.create(:tag => 'fuckbutter', :abusive => true)
Tag.create(:tag => 'fucked', :abusive => true)
Tag.create(:tag => 'fucker', :abusive => true)
Tag.create(:tag => 'fuckersucker', :abusive => true)
Tag.create(:tag => 'fuckface', :abusive => true)
Tag.create(:tag => 'fuckhead', :abusive => true)
Tag.create(:tag => 'fuckhole', :abusive => true)
Tag.create(:tag => 'fuckin', :abusive => true)
Tag.create(:tag => 'fucking', :abusive => true)
Tag.create(:tag => 'fucknut', :abusive => true)
Tag.create(:tag => 'fucknutt', :abusive => true)
Tag.create(:tag => 'fuckoff', :abusive => true)
Tag.create(:tag => 'fucks', :abusive => true)
Tag.create(:tag => 'fuckstick', :abusive => true)
Tag.create(:tag => 'fucktard', :abusive => true)
Tag.create(:tag => 'fucktart', :abusive => true)
Tag.create(:tag => 'fuckup', :abusive => true)
Tag.create(:tag => 'fuckwad', :abusive => true)
Tag.create(:tag => 'fuckwit', :abusive => true)
Tag.create(:tag => 'fuckwitt', :abusive => true)
Tag.create(:tag => 'fudgepacker', :abusive => true)
Tag.create(:tag => 'gay', :abusive => true)
Tag.create(:tag => 'gayass', :abusive => true)
Tag.create(:tag => 'gaybob', :abusive => true)
Tag.create(:tag => 'gaydo', :abusive => true)
Tag.create(:tag => 'gayfuck', :abusive => true)
Tag.create(:tag => 'gayfuckist', :abusive => true)
Tag.create(:tag => 'gaylord', :abusive => true)
Tag.create(:tag => 'gaytard', :abusive => true)
Tag.create(:tag => 'gaywad', :abusive => true)
Tag.create(:tag => 'goddamn', :abusive => true)
Tag.create(:tag => 'goddamnit', :abusive => true)
Tag.create(:tag => 'gooch', :abusive => true)
Tag.create(:tag => 'gook', :abusive => true)
Tag.create(:tag => 'gringo', :abusive => true)
Tag.create(:tag => 'guido', :abusive => true)
Tag.create(:tag => 'handjob', :abusive => true)
Tag.create(:tag => 'hard on', :abusive => true)
Tag.create(:tag => 'heeb', :abusive => true)
Tag.create(:tag => 'hell', :abusive => true)
Tag.create(:tag => 'ho', :abusive => true)
Tag.create(:tag => 'hoe', :abusive => true)
Tag.create(:tag => 'homo', :abusive => true)
Tag.create(:tag => 'homodumbshit', :abusive => true)
Tag.create(:tag => 'honkey', :abusive => true)
Tag.create(:tag => 'humping', :abusive => true)
Tag.create(:tag => 'jackass', :abusive => true)
Tag.create(:tag => 'jagoff', :abusive => true)
Tag.create(:tag => 'jap', :abusive => true)
Tag.create(:tag => 'jerk off', :abusive => true)
Tag.create(:tag => 'jerkass', :abusive => true)
Tag.create(:tag => 'jigaboo', :abusive => true)
Tag.create(:tag => 'jizz', :abusive => true)
Tag.create(:tag => 'jungle bunny', :abusive => true)
Tag.create(:tag => 'junglebunny', :abusive => true)
Tag.create(:tag => 'kike', :abusive => true)
Tag.create(:tag => 'kooch', :abusive => true)
Tag.create(:tag => 'kootch', :abusive => true)
Tag.create(:tag => 'kraut', :abusive => true)
Tag.create(:tag => 'kunt', :abusive => true)
Tag.create(:tag => 'kyke', :abusive => true)
Tag.create(:tag => 'lameass', :abusive => true)
Tag.create(:tag => 'lardass', :abusive => true)
Tag.create(:tag => 'lesbian', :abusive => true)
Tag.create(:tag => 'lesbo', :abusive => true)
Tag.create(:tag => 'lezzie', :abusive => true)
Tag.create(:tag => 'mcfagget', :abusive => true)
Tag.create(:tag => 'mick', :abusive => true)
Tag.create(:tag => 'minge', :abusive => true)
Tag.create(:tag => 'mothafucka', :abusive => true)
Tag.create(:tag => 'mothafuckin', :abusive => true)
Tag.create(:tag => 'motherfucker', :abusive => true)
Tag.create(:tag => 'motherfucking', :abusive => true)
Tag.create(:tag => 'muff', :abusive => true)
Tag.create(:tag => 'muffdiver', :abusive => true)
Tag.create(:tag => 'munging', :abusive => true)
Tag.create(:tag => 'negro', :abusive => true)
Tag.create(:tag => 'nigaboo', :abusive => true)
Tag.create(:tag => 'nigga', :abusive => true)
Tag.create(:tag => 'nigger', :abusive => true)
Tag.create(:tag => 'niggers', :abusive => true)
Tag.create(:tag => 'niglet', :abusive => true)
Tag.create(:tag => 'nut sack', :abusive => true)
Tag.create(:tag => 'nutsack', :abusive => true)
Tag.create(:tag => 'paki', :abusive => true)
Tag.create(:tag => 'panooch', :abusive => true)
Tag.create(:tag => 'pecker', :abusive => true)
Tag.create(:tag => 'peckerhead', :abusive => true)
Tag.create(:tag => 'penis', :abusive => true)
Tag.create(:tag => 'penisbanger', :abusive => true)
Tag.create(:tag => 'penisfucker', :abusive => true)
Tag.create(:tag => 'penispuffer', :abusive => true)
Tag.create(:tag => 'piss', :abusive => true)
Tag.create(:tag => 'pissed', :abusive => true)
Tag.create(:tag => 'pissed off', :abusive => true)
Tag.create(:tag => 'pissflaps', :abusive => true)
Tag.create(:tag => 'polesmoker', :abusive => true)
Tag.create(:tag => 'pollock', :abusive => true)
Tag.create(:tag => 'poon', :abusive => true)
Tag.create(:tag => 'poonani', :abusive => true)
Tag.create(:tag => 'poonany', :abusive => true)
Tag.create(:tag => 'poontang', :abusive => true)
Tag.create(:tag => 'porch monkey', :abusive => true)
Tag.create(:tag => 'porchmonkey', :abusive => true)
Tag.create(:tag => 'prick', :abusive => true)
Tag.create(:tag => 'punanny', :abusive => true)
Tag.create(:tag => 'punta', :abusive => true)
Tag.create(:tag => 'pussies', :abusive => true)
Tag.create(:tag => 'pussy', :abusive => true)
Tag.create(:tag => 'pussylicking', :abusive => true)
Tag.create(:tag => 'puto', :abusive => true)
Tag.create(:tag => 'queef', :abusive => true)
Tag.create(:tag => 'queer', :abusive => true)
Tag.create(:tag => 'queerbait', :abusive => true)
Tag.create(:tag => 'queerhole', :abusive => true)
Tag.create(:tag => 'renob', :abusive => true)
Tag.create(:tag => 'rimjob', :abusive => true)
Tag.create(:tag => 'ruski', :abusive => true)
Tag.create(:tag => 'sand nigger', :abusive => true)
Tag.create(:tag => 'sandnigger', :abusive => true)
Tag.create(:tag => 'schlong', :abusive => true)
Tag.create(:tag => 'scrote', :abusive => true)
Tag.create(:tag => 'shit', :abusive => true)
Tag.create(:tag => 'shitass', :abusive => true)
Tag.create(:tag => 'shitbag', :abusive => true)
Tag.create(:tag => 'shitbagger', :abusive => true)
Tag.create(:tag => 'shitbrains', :abusive => true)
Tag.create(:tag => 'shitbreath', :abusive => true)
Tag.create(:tag => 'shitcanned', :abusive => true)
Tag.create(:tag => 'shitcunt', :abusive => true)
Tag.create(:tag => 'shitdick', :abusive => true)
Tag.create(:tag => 'shitface', :abusive => true)
Tag.create(:tag => 'shitfaced', :abusive => true)
Tag.create(:tag => 'shithead', :abusive => true)
Tag.create(:tag => 'shithole', :abusive => true)
Tag.create(:tag => 'shithouse', :abusive => true)
Tag.create(:tag => 'shitspitter', :abusive => true)
Tag.create(:tag => 'shitstain', :abusive => true)
Tag.create(:tag => 'shitter', :abusive => true)
Tag.create(:tag => 'shittiest', :abusive => true)
Tag.create(:tag => 'shitting', :abusive => true)
Tag.create(:tag => 'shitty', :abusive => true)
Tag.create(:tag => 'shiz', :abusive => true)
Tag.create(:tag => 'shiznit', :abusive => true)
Tag.create(:tag => 'skank', :abusive => true)
Tag.create(:tag => 'skeet', :abusive => true)
Tag.create(:tag => 'skullfuck', :abusive => true)
Tag.create(:tag => 'slut', :abusive => true)
Tag.create(:tag => 'slutbag', :abusive => true)
Tag.create(:tag => 'smeg', :abusive => true)
Tag.create(:tag => 'snatch', :abusive => true)
Tag.create(:tag => 'spic', :abusive => true)
Tag.create(:tag => 'spick', :abusive => true)
Tag.create(:tag => 'splooge', :abusive => true)
Tag.create(:tag => 'spook', :abusive => true)
Tag.create(:tag => 'suckass', :abusive => true)
Tag.create(:tag => 'tard', :abusive => true)
Tag.create(:tag => 'testicle', :abusive => true)
Tag.create(:tag => 'thundercunt', :abusive => true)
Tag.create(:tag => 'tit', :abusive => true)
Tag.create(:tag => 'titfuck', :abusive => true)
Tag.create(:tag => 'tits', :abusive => true)
Tag.create(:tag => 'tittyfuck', :abusive => true)
Tag.create(:tag => 'twat', :abusive => true)
Tag.create(:tag => 'twatlips', :abusive => true)
Tag.create(:tag => 'twats', :abusive => true)
Tag.create(:tag => 'twatwaffle', :abusive => true)
Tag.create(:tag => 'unclefucker', :abusive => true)
Tag.create(:tag => 'va-j-j', :abusive => true)
Tag.create(:tag => 'vag', :abusive => true)
Tag.create(:tag => 'vagina', :abusive => true)
Tag.create(:tag => 'vajayjay', :abusive => true)
Tag.create(:tag => 'vjayjay', :abusive => true)
Tag.create(:tag => 'wank', :abusive => true)
Tag.create(:tag => 'wankjob', :abusive => true)
Tag.create(:tag => 'wetback', :abusive => true)
Tag.create(:tag => 'whore', :abusive => true)
Tag.create(:tag => 'whorebag', :abusive => true)
Tag.create(:tag => 'whoreface', :abusive => true)
Tag.create(:tag => 'wop', :abusive => true)
